pluginManagement {
    repositories {
        **ARTIFACTORYREPOSITORY**
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

include ':launcher', ':unityLibrary'
**INCLUDES**

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        **ARTIFACTORYREPOSITORY**
        google()
        mavenCentral()
// Android Resolver Repos Start
        def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace("\\", "/")
        maven {
            url (unityProjectPath + "/Assets/LeapDataWeb/Runtime/Firebase/m2repository") // Packages/com.lefortech.data.web/Runtime/Firebase/Editor/AppDependencies.xml:26, Packages/com.lefortech.data.web/Runtime/Firebase/Editor/AuthDependencies.xml:24, Packages/com.lefortech.data.web/Runtime/Firebase/Editor/MessagingDependencies.xml:28
        }
        maven {
            url (unityProjectPath + "/Assets/Maven/Runtime/Firebase/m2repository") // Packages/com.lefortech.data.web/Runtime/Firebase/Editor/AppDependencies.xml:26, Packages/com.lefortech.data.web/Runtime/Firebase/Editor/AuthDependencies.xml:24, Packages/com.lefortech.data.web/Runtime/Firebase/Editor/MessagingDependencies.xml:28
        }
        mavenLocal()
// Android Resolver Repos End
        flatDir {
            dirs "${project(':unityLibrary').projectDir}/libs"
        }
    }
}
